<?php

namespace Biocare\CarrierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HttpApiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HttpApiRepository extends EntityRepository
{
}
