<?php

namespace Biocare\CallBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CallRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallRegisterRepository extends EntityRepository
{
}
