biocare_carrier:
    resource: "@BiocareCarrierBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_connection:
    resource: "@BiocareConnectionBundle/Controller/"
    type:     annotation
    prefix:   /

