yellowknife_security:
    resource: "@YellowknifeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_admin:
    resource: "@BiocareAdminBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_campaign:
    resource: "@BiocareCampaignBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_price:
    resource: "@BiocarePriceBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_http_api:
    resource: "@BiocareHttpApiBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_storage:
    resource: "@BiocareStorageBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_product:
    resource: "@BiocareProductBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_order:
    resource: "@BiocareOrderBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_address:
    resource: "@BiocareAddressBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_customer:
    resource: "@BiocareCustomerBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_call:
    resource: "@BiocareCallBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_panel:
    resource: "@BiocarePanelBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_carrier:
    resource: "@BiocareCarrierBundle/Controller/"
    type:     annotation
    prefix:   /

#biocare_connection:
#    resource: "@BiocareConnectionBundle/Controller/"
#    type:     annotation
#    prefix:   /

