biocare_customer:
    resource: "@BiocareCustomerBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_call:
    resource: "@BiocareCallBundle/Controller/"
    type:     annotation
    prefix:   /

biocare_panel:
    resource: "@BiocarePanelBundle/Controller/"
    type:     annotation
    prefix:   /

#biocare_carrier:
#    resource: "@BiocareCarrierBundle/Controller/"
#    type:     annotation
#    prefix:   /

#biocare_connection:
#    resource: "@BiocareConnectionBundle/Controller/"
#    type:     annotation
#    prefix:   /

