security:
    role_hierarchy:
        ROLE_ADMIN: 	ROLE_USER

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext

    providers:
        in_memory:
            memory:
                users:
                    gontarski:
                        password: 123123
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        default:
            pattern:  ^/
            http_basic: ~

    access_control:
        - { path: ^/,               roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,               roles: ROLE_ADMIN }
        
