security:
    role_hierarchy:
        ROLE_ADMIN: 	ROLE_USER

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext

    providers:
        in_memory:
            memory:
                users:
                    gontarski:
                        password: 123123
                        roles: 'ROLE_ADMIN'                        
                    filip:
                        password: 123123
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js|httpapi)/
            security: false
        default:
            pattern:  ^/
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager

    access_control:
        - { path: ^/httpapi, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
        
