security:
    role_hierarchy:
        ROLE_SUPERVISOR:    ROLE_USER
        ROLE_ADMIN:         ROLE_SUPERVISOR

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
        Yellowknife\SecurityBundle\Entity\User:
            algorithm: plaintext
            
    providers:       
        chain_provider:
            chain:
                providers: [in_memory, db_provider]
        db_provider:
            entity:
                class: YellowknifeSecurityBundle:User

        in_memory:
            memory:
                users:
                    gontarski:
                        password: 123123
                        roles: 'ROLE_ADMIN'                        
                    filip:
                        password: 123123
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js|httpapi)/
            security: false
        default:
            pattern:  ^/
            anonymous: ~
            http_basic: ~
            provider: chain_provider
            logout:
                path:   /logout
                target: /login
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
                use_referer: false
                success_handler: yellowknife_security.login

    access_control:
        - { path: ^/httpapi, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/callcenter, roles: ROLE_SUPERVISOR }
        - { path: ^/, roles: ROLE_USER }
        
