# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name: 
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    calllistener:
        class: Biocare\CallBundle\Listener\CallListener
        scope: prototype
        calls: 
            - [ register ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
             - [ setAnnotationReader, [ @annotation_reader ] ]
             
    gedmo.listener.ip_traceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
             - [ setAnnotationReader, [ @annotation_reader ] ]
             - [ setIpValue, [ "127.0.0.1" ] ]
                          
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
             - [ setAnnotationReader, [ @annotation_reader ] ] 
             - [ setUserValue, [ 'nobody' ] ]