<?php

namespace Yellowknife\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLogRepository extends EntityRepository
{
}
