<?php

namespace Biocare\HttpApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuB2CPLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuB2CPLRepository extends EntityRepository
{
}
